### ISSUE TITLE
Looking forward to the checkpoint & code release!

### ISSUE THREAD

**Issue by jonasjunzhang** [2toinf/IVM#1]
Hi, great work!
I've been looking forward to the release of the model checkpoints and code since your paper is out. Any future plans on the release time? By the way, do you plan to release the dataset as well?

**Comment by 2toinf** [comment]
Sure! Sorry for the delay in publishing the ckpt and datasets, we will release them soon

**Comment by Facebear-ljx** [comment]
> Hi, great work! I've been looking forward to the release of the model checkpoints and code since your paper is out. Any future plans on the release time? By the way, do you plan to release the dataset as well?

Hi! We have released our model and data. Feel free to try it!
